"""m6 board meetings

Revision ID: 687a7dd474e2
Revises: ba542d46de71
Create Date: 2026-10-03 22:03:43.523868

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "687a7dd474e2"
down_revision: str | Sequence[str] | None = "ba542d46de71"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "board_meetings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("meeting_date", sa.Date(), nullable=False),
        sa.Column("purpose", sa.String(length=300), nullable=False),
        sa.Column("description", sa.String(length=2000), nullable=False),
        sa.Column("is_results", sa.Boolean(), nullable=False),
        sa.Column("announced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "first_seen",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("symbol", "meeting_date", "purpose"),
    )
    op.create_index(
        op.f("ix_board_meetings_meeting_date"), "board_meetings", ["meeting_date"], unique=False
    )
    op.create_index(op.f("ix_board_meetings_symbol"), "board_meetings", ["symbol"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_board_meetings_symbol"), table_name="board_meetings")
    op.drop_index(op.f("ix_board_meetings_meeting_date"), table_name="board_meetings")
    op.drop_table("board_meetings")
    # ### end Alembic commands ###
