"""m7 retired paper accounts

Revision ID: 5ba277ef8bcf
Revises: dc8783d01ad3
Create Date: 2026-10-04 10:49:02.827419

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5ba277ef8bcf"
down_revision: str | Sequence[str] | None = "dc8783d01ad3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "paper_accounts", sa.Column("retired_reason", sa.String(length=300), nullable=True)
    )
    op.add_column("paper_accounts", sa.Column("retired_on", sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("paper_accounts", "retired_on")
    op.drop_column("paper_accounts", "retired_reason")
    # ### end Alembic commands ###
