"""ui1b trade plans and watchlist

Revision ID: 546e01fe847d
Revises: 5ba277ef8bcf
Create Date: 2026-10-05 18:37:49.776183

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "546e01fe847d"
down_revision: str | Sequence[str] | None = "5ba277ef8bcf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "watchlist",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ticker", sa.String(length=32), nullable=False),
        sa.Column("alert_price", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("alert_direction", sa.String(length=8), nullable=True),
        sa.Column("note", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ticker"),
    )
    op.create_table(
        "trade_plans",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ticker", sa.String(length=32), nullable=False),
        sa.Column("signal_id", sa.UUID(), nullable=True),
        sa.Column("supersedes_id", sa.Integer(), nullable=True),
        sa.Column("tier", sa.String(length=16), nullable=False),
        sa.Column("entry", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("stop", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("target1", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("target2", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("shares", sa.Integer(), nullable=False),
        sa.Column("risk_amount", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("position_value", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("reward_risk_t2", sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column("stop_distance_pct", sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column("mood", sa.String(length=16), nullable=True),
        sa.Column("reason", sa.String(), nullable=False),
        sa.Column("data_as_of", sa.Date(), nullable=True),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("checklist", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["signal_id"],
            ["signals.signal_id"],
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_id"],
            ["trade_plans.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_trade_plans_signal_id"), "trade_plans", ["signal_id"], unique=False)
    op.create_index(op.f("ix_trade_plans_ticker"), "trade_plans", ["ticker"], unique=False)
    op.add_column("journal_entries", sa.Column("plan_id", sa.Integer(), nullable=True))
    op.create_index(
        op.f("ix_journal_entries_plan_id"), "journal_entries", ["plan_id"], unique=False
    )
    op.create_foreign_key(
        "journal_entries_plan_id_fkey", "journal_entries", "trade_plans", ["plan_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("journal_entries_plan_id_fkey", "journal_entries", type_="foreignkey")
    op.drop_index(op.f("ix_journal_entries_plan_id"), table_name="journal_entries")
    op.drop_column("journal_entries", "plan_id")
    op.drop_index(op.f("ix_trade_plans_ticker"), table_name="trade_plans")
    op.drop_index(op.f("ix_trade_plans_signal_id"), table_name="trade_plans")
    op.drop_table("trade_plans")
    op.drop_table("watchlist")
    # ### end Alembic commands ###
