"""M3 backtester: runs, trades, variants

Revision ID: 4d47f594edc5
Revises: 68b13b107e3c
Create Date: 2026-10-02 21:36:42.160261

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4d47f594edc5"
down_revision: str | Sequence[str] | None = "68b13b107e3c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "backtest_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("strategy_key", sa.String(length=64), nullable=False),
        sa.Column("strategy_version", sa.String(length=64), nullable=False),
        sa.Column("strategy_name", sa.String(length=200), nullable=False),
        sa.Column("tier", sa.String(length=16), nullable=False),
        sa.Column("data_start", sa.Date(), nullable=False),
        sa.Column("data_end", sa.Date(), nullable=False),
        sa.Column("oos_start", sa.Date(), nullable=False),
        sa.Column("holdout_start", sa.Date(), nullable=False),
        sa.Column("live_eligible", sa.Boolean(), nullable=False),
        sa.Column("fingerprint", sa.String(length=32), nullable=False),
        sa.Column("duration_seconds", sa.Numeric(precision=10, scale=3), nullable=True),
        sa.Column("summary", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("equity", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_backtest_runs_strategy_key"), "backtest_runs", ["strategy_key"], unique=False
    )
    op.create_table(
        "backtest_trades",
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("segment", sa.String(length=16), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("variant", sa.String(length=200), nullable=False),
        sa.Column("signal_date", sa.Date(), nullable=False),
        sa.Column("entry_date", sa.Date(), nullable=False),
        sa.Column("exit_date", sa.Date(), nullable=False),
        sa.Column("entry_price", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("stop_price", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("target_price", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("exit_price", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("shares", sa.Integer(), nullable=False),
        sa.Column("exit_reason", sa.String(length=100), nullable=False),
        sa.Column("gross_pnl", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("charges", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("dividends", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("net_pnl", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("r_multiple", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("regime", sa.String(length=16), nullable=False),
        sa.Column("score", sa.Numeric(precision=5, scale=1), nullable=False),
        sa.Column("sessions", sa.Integer(), nullable=False),
        sa.Column("open_at_end", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["backtest_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("run_id", "seq"),
    )
    op.create_table(
        "backtest_variants",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("window", sa.String(length=32), nullable=False),
        sa.Column("label", sa.String(length=200), nullable=False),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("train_start", sa.Date(), nullable=False),
        sa.Column("train_end", sa.Date(), nullable=False),
        sa.Column("trades", sa.Integer(), nullable=False),
        sa.Column("expectancy_r", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("sharpe", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("chosen", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["backtest_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_backtest_variants_run_id"), "backtest_variants", ["run_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_backtest_variants_run_id"), table_name="backtest_variants")
    op.drop_table("backtest_variants")
    op.drop_table("backtest_trades")
    op.drop_index(op.f("ix_backtest_runs_strategy_key"), table_name="backtest_runs")
    op.drop_table("backtest_runs")
    # ### end Alembic commands ###
