"""M4 paper trading: accounts, signals, paper trades and days

Revision ID: e5c458314e61
Revises: 4d47f594edc5
Create Date: 2026-10-03 15:12:01.596599

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e5c458314e61"
down_revision: str | Sequence[str] | None = "4d47f594edc5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "paper_accounts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("strategy_key", sa.String(length=64), nullable=False),
        sa.Column("strategy_version", sa.String(length=64), nullable=False),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("params_label", sa.String(length=200), nullable=False),
        sa.Column("backtest_run_id", sa.Integer(), nullable=False),
        sa.Column("live_eligible", sa.Boolean(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("capital", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("rules", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("last_date", sa.Date(), nullable=True),
        sa.Column("summary", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["backtest_run_id"],
            ["backtest_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_paper_accounts_strategy_key"), "paper_accounts", ["strategy_key"], unique=False
    )
    op.create_table(
        "paper_days",
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("trade_date", sa.Date(), nullable=False),
        sa.Column("equity", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("drawdown_pct", sa.Numeric(precision=8, scale=3), nullable=False),
        sa.Column("heat_pct", sa.Numeric(precision=8, scale=3), nullable=False),
        sa.Column("open_positions", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["account_id"], ["paper_accounts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("account_id", "trade_date"),
    )
    op.create_table(
        "paper_trades",
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("signal_id", sa.UUID(), nullable=True),
        sa.Column("ticker", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("signal_date", sa.Date(), nullable=False),
        sa.Column("entry_date", sa.Date(), nullable=False),
        sa.Column("entry_price", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("initial_stop", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("target_t1", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("shares", sa.Integer(), nullable=False),
        sa.Column("current_stop", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("last_close", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("shares_held", sa.Integer(), nullable=False),
        sa.Column("exit_date", sa.Date(), nullable=True),
        sa.Column("exit_price", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("exit_reason", sa.String(length=100), nullable=True),
        sa.Column("charges", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("dividends", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("net_pnl", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("r_multiple", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("sessions", sa.Integer(), nullable=False),
        sa.Column("exits", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(["account_id"], ["paper_accounts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("account_id", "seq"),
    )
    op.create_table(
        "signals",
        sa.Column("signal_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("ticker", sa.String(length=32), nullable=False),
        sa.Column("signal_date", sa.Date(), nullable=False),
        sa.Column("research_only", sa.Boolean(), nullable=False),
        sa.Column("late", sa.Boolean(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["paper_accounts.id"],
        ),
        sa.PrimaryKeyConstraint("signal_id"),
        sa.UniqueConstraint("account_id", "signal_date", "ticker", "version"),
    )
    op.create_index(op.f("ix_signals_account_id"), "signals", ["account_id"], unique=False)
    op.create_index(op.f("ix_signals_signal_date"), "signals", ["signal_date"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_signals_signal_date"), table_name="signals")
    op.drop_index(op.f("ix_signals_account_id"), table_name="signals")
    op.drop_table("signals")
    op.drop_table("paper_trades")
    op.drop_table("paper_days")
    op.drop_index(op.f("ix_paper_accounts_strategy_key"), table_name="paper_accounts")
    op.drop_table("paper_accounts")
    # ### end Alembic commands ###
