"""M2 scanner: index closes, security status, surveillance, symbol changes, scans

Revision ID: 68b13b107e3c
Revises: 7b1f2c9d4e10
Create Date: 2026-10-02 13:03:50

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "68b13b107e3c"
down_revision: str | Sequence[str] | None = "7b1f2c9d4e10"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "index_bars",
        sa.Column("index_name", sa.String(length=64), nullable=False),
        sa.Column("trade_date", sa.Date(), nullable=False),
        sa.Column("open", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("high", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("low", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("close", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.PrimaryKeyConstraint("index_name", "trade_date"),
    )
    op.create_table(
        "scan_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("trade_date", sa.Date(), nullable=False),
        sa.Column("score_version", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("universe_size", sa.Integer(), nullable=False),
        sa.Column("duration_seconds", sa.Numeric(precision=10, scale=3), nullable=True),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("trade_date", "score_version"),
    )
    op.create_index(op.f("ix_scan_runs_trade_date"), "scan_runs", ["trade_date"], unique=False)
    op.create_table(
        "symbol_changes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("old_symbol", sa.String(length=32), nullable=False),
        sa.Column("new_symbol", sa.String(length=32), nullable=False),
        sa.Column("change_date", sa.Date(), nullable=False),
        sa.Column("company_name", sa.String(length=200), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("old_symbol", "new_symbol", "change_date"),
    )
    op.create_index(
        op.f("ix_symbol_changes_new_symbol"), "symbol_changes", ["new_symbol"], unique=False
    )
    op.create_index(
        op.f("ix_symbol_changes_old_symbol"), "symbol_changes", ["old_symbol"], unique=False
    )
    op.create_table(
        "scan_results",
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("instrument_id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("score", sa.Numeric(precision=5, scale=1), nullable=False),
        sa.Column("close", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("in_nifty500", sa.Boolean(), nullable=False),
        sa.Column("sector", sa.String(length=100), nullable=True),
        sa.Column("components", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("indicators", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
        ),
        sa.ForeignKeyConstraint(["run_id"], ["scan_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("run_id", "instrument_id"),
    )
    op.create_table(
        "security_status",
        sa.Column("instrument_id", sa.Integer(), nullable=False),
        sa.Column("trade_date", sa.Date(), nullable=False),
        sa.Column("series", sa.String(length=4), nullable=False),
        sa.Column("price_band", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("remarks", sa.String(length=200), nullable=True),
        sa.Column("gsm_stage", sa.String(length=32), nullable=True),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
        ),
        sa.PrimaryKeyConstraint("instrument_id", "trade_date"),
    )
    op.create_index(
        op.f("ix_security_status_trade_date"), "security_status", ["trade_date"], unique=False
    )
    op.create_table(
        "surveillance_flags",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("instrument_id", sa.Integer(), nullable=False),
        sa.Column("measure", sa.String(length=16), nullable=False),
        sa.Column("stage", sa.String(length=64), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_surveillance_flags_instrument_id"),
        "surveillance_flags",
        ["instrument_id"],
        unique=False,
    )
    op.create_unique_constraint(
        "uq_index_memberships_period",
        "index_memberships",
        ["index_name", "instrument_id", "start_date"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_index_memberships_period", "index_memberships", type_="unique")
    op.drop_index(op.f("ix_surveillance_flags_instrument_id"), table_name="surveillance_flags")
    op.drop_table("surveillance_flags")
    op.drop_index(op.f("ix_security_status_trade_date"), table_name="security_status")
    op.drop_table("security_status")
    op.drop_table("scan_results")
    op.drop_index(op.f("ix_symbol_changes_old_symbol"), table_name="symbol_changes")
    op.drop_index(op.f("ix_symbol_changes_new_symbol"), table_name="symbol_changes")
    op.drop_table("symbol_changes")
    op.drop_index(op.f("ix_scan_runs_trade_date"), table_name="scan_runs")
    op.drop_table("scan_runs")
    op.drop_table("index_bars")
    # ### end Alembic commands ###
