"""m7 tradebook fills

Revision ID: dc8783d01ad3
Revises: b04b05527b25
Create Date: 2026-10-04 10:42:06.713180

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dc8783d01ad3"
down_revision: str | Sequence[str] | None = "b04b05527b25"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "journal_fills",
        sa.Column("charges_estimated", sa.Boolean(), server_default="false", nullable=False),
    )
    op.add_column(
        "journal_fills",
        sa.Column("source", sa.String(length=16), server_default="manual", nullable=False),
    )
    op.add_column(
        "journal_fills", sa.Column("broker_trade_id", sa.String(length=64), nullable=True)
    )
    op.create_unique_constraint(
        "uq_journal_fills_broker_trade_id", "journal_fills", ["broker_trade_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_journal_fills_broker_trade_id", "journal_fills", type_="unique")
    op.drop_column("journal_fills", "broker_trade_id")
    op.drop_column("journal_fills", "source")
    op.drop_column("journal_fills", "charges_estimated")
    # ### end Alembic commands ###
