"""initial schema

Revision ID: e3d629689957
Revises:
Create Date: 2026-09-30 17:58:07.168566

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e3d629689957"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "data_quality_reports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("trade_date", sa.Date(), nullable=False),
        sa.Column("status", sa.Enum("pass", "warn", "fail", name="quality_status"), nullable=False),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_data_quality_reports_trade_date"),
        "data_quality_reports",
        ["trade_date"],
        unique=False,
    )
    op.create_table(
        "instruments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("exchange", sa.Enum("NSE", "BSE", name="exchange"), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("series", sa.String(length=4), nullable=False),
        sa.Column("isin", sa.String(length=12), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=True),
        sa.Column("sector", sa.String(length=100), nullable=True),
        sa.Column("industry", sa.String(length=100), nullable=True),
        sa.Column("listing_date", sa.Date(), nullable=True),
        sa.Column("delisting_date", sa.Date(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("exchange", "symbol", "series"),
    )
    op.create_index(op.f("ix_instruments_isin"), "instruments", ["isin"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "corporate_actions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("instrument_id", sa.Integer(), nullable=False),
        sa.Column("ex_date", sa.Date(), nullable=False),
        sa.Column(
            "action_type",
            sa.Enum("split", "bonus", "rights", "dividend", "other", name="corporate_action_type"),
            nullable=False,
        ),
        sa.Column("ratio_new", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("ratio_old", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("amount", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("raw_text", sa.String(length=500), nullable=True),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_corporate_actions_ex_date"), "corporate_actions", ["ex_date"], unique=False
    )
    op.create_index(
        op.f("ix_corporate_actions_instrument_id"),
        "corporate_actions",
        ["instrument_id"],
        unique=False,
    )
    op.create_table(
        "daily_bars",
        sa.Column("instrument_id", sa.Integer(), nullable=False),
        sa.Column("trade_date", sa.Date(), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("open", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("high", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("low", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("close", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("prev_close", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("volume", sa.BigInteger(), nullable=False),
        sa.Column("turnover", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
        ),
        sa.PrimaryKeyConstraint("instrument_id", "trade_date", "source"),
    )
    op.create_index("ix_daily_bars_trade_date", "daily_bars", ["trade_date"], unique=False)
    op.create_table(
        "index_memberships",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("index_name", sa.String(length=64), nullable=False),
        sa.Column("instrument_id", sa.Integer(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_index_memberships_index_name"), "index_memberships", ["index_name"], unique=False
    )
    op.create_index(
        op.f("ix_index_memberships_instrument_id"),
        "index_memberships",
        ["instrument_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_index_memberships_instrument_id"), table_name="index_memberships")
    op.drop_index(op.f("ix_index_memberships_index_name"), table_name="index_memberships")
    op.drop_table("index_memberships")
    op.drop_index("ix_daily_bars_trade_date", table_name="daily_bars")
    op.drop_table("daily_bars")
    op.drop_index(op.f("ix_corporate_actions_instrument_id"), table_name="corporate_actions")
    op.drop_index(op.f("ix_corporate_actions_ex_date"), table_name="corporate_actions")
    op.drop_table("corporate_actions")
    op.drop_table("users")
    op.drop_index(op.f("ix_instruments_isin"), table_name="instruments")
    op.drop_table("instruments")
    op.drop_index(op.f("ix_data_quality_reports_trade_date"), table_name="data_quality_reports")
    op.drop_table("data_quality_reports")
    for enum_name in ("quality_status", "exchange", "corporate_action_type"):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
