"""m6 announcements

Revision ID: d69b3418af6b
Revises: 687a7dd474e2
Create Date: 2026-10-03 22:30:50.806289

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d69b3418af6b"
down_revision: str | Sequence[str] | None = "687a7dd474e2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "announcements",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("subject", sa.String(length=200), nullable=True),
        sa.Column("text", sa.String(length=2000), nullable=False),
        sa.Column("digest", sa.String(length=32), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("symbol", "day", "digest"),
    )
    op.create_index(op.f("ix_announcements_day"), "announcements", ["day"], unique=False)
    op.create_index(op.f("ix_announcements_symbol"), "announcements", ["symbol"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_announcements_symbol"), table_name="announcements")
    op.drop_index(op.f("ix_announcements_day"), table_name="announcements")
    op.drop_table("announcements")
    # ### end Alembic commands ###
